### ISSUE TITLE
Javascript error / Infinite loading

### ISSUE THREAD

**Issue by b12e** [PatMurrayDEV/apple-music-history#2]
<img width="867" alt="schermafbeelding 2018-12-11 om 21 56 15" src="https://user-images.githubusercontent.com/1340823/49830212-d4140580-fd90-11e8-9121-a27a17fc958d.png">
Whenever I try to select my CSV, almost instantly afterwards selecting it it throws a Javascript error on line 283 in computation.js:

                       ` heatmapData[dayint][hoursint] = Number(heatmapData[dayint][hoursint]) + Number(play["Play Duration Milliseconds"]);`

For some reason, it can't read a value, and therefore throws a NaN error:

> Uncaught TypeError: Cannot read property 'NaN' of undefined

Please ask me for the CSV if needed.

**Comment by PatMurrayDEV** [comment]
Hey, I made a change today that ignores songs with no `"Play Duration Milliseconds"` in them. This *should* fix this issue—incidentally, not directly—mind letting me know if this fix works for you? 

If not we'll explore tackling this problem directly

**Comment by enzotneto** [comment]
Hi, as b12e everytime a tried upload my .cvs file i get a infinite loading

**Comment by enzotneto** [comment]
I'm not good as you guys at tech, so i don't know whats wrong

**Comment by enzotneto** [comment]
2(index):1 Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See https://www.chromestatus.com/feature/5527160148197376 for more details
rightclick.js:25 allow right click processing https://music.patmurray.co/
common.js:263 Uncaught ReferenceError: $st is not defined
    at common.js:263
main.2072501c.chunk.js:1 Uncaught TypeError: Cannot read property 'NaN' of undefined
    at Function.value (main.2072501c.chunk.js:1)
    at main.2072501c.chunk.js:1
2new_rightclick.js:87 Uncaught TypeError: event.cancelBubble is not a function
    at HTMLDocument.bringBackDefault (new_rightclick.js:87)

That was what i get

**Comment by b12e** [comment]
Great success!
<img width="1586" alt="schermafbeelding 2018-12-12 om 08 11 30" src="https://user-images.githubusercontent.com/1340823/49852866-9db4a580-fde5-11e8-8541-f72d28330e6a.png">

**Comment by b12e** [comment]
<img width="677" alt="schermafbeelding 2018-12-12 om 08 20 58" src="https://user-images.githubusercontent.com/1340823/49853268-e3be3900-fde6-11e8-8194-0a08013147ef.png">
I should probably open a new incident, but isn't it more logical to show this chronological oldest month to newest month, and hide the "nan" month?

![image](https://user-images.githubusercontent.com/1340823/49853310-051f2500-fde7-11e8-950e-768f4ac64fbe.png)
Same for "NaN" in the last one, isn't it more logical to hide that year?

![image](https://user-images.githubusercontent.com/1340823/49853439-6fd06080-fde7-11e8-97a0-8ec1668880b0.png)
This is also nice, but everything's so tiny with all the empty Spotify months in between... :)

**Comment by PatMurrayDEV** [comment]
Hi yeah I’ll open a new issue for that. But definitely should be sorted chronologically, not sure what’s happening there. Thanks for your patience

**Comment by PatMurrayDEV** [comment]
This has been carried over to #3
